/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AEgaleT2 extends PT2
{
    private PT2 _t2_;
    private TEgale _egale_;
    private PT3 _t3_;

    public AEgaleT2()
    {
        // Constructor
    }

    public AEgaleT2(
        @SuppressWarnings("hiding") PT2 _t2_,
        @SuppressWarnings("hiding") TEgale _egale_,
        @SuppressWarnings("hiding") PT3 _t3_)
    {
        // Constructor
        setT2(_t2_);

        setEgale(_egale_);

        setT3(_t3_);

    }

    @Override
    public Object clone()
    {
        return new AEgaleT2(
            cloneNode(this._t2_),
            cloneNode(this._egale_),
            cloneNode(this._t3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEgaleT2(this);
    }

    public PT2 getT2()
    {
        return this._t2_;
    }

    public void setT2(PT2 node)
    {
        if(this._t2_ != null)
        {
            this._t2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t2_ = node;
    }

    public TEgale getEgale()
    {
        return this._egale_;
    }

    public void setEgale(TEgale node)
    {
        if(this._egale_ != null)
        {
            this._egale_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._egale_ = node;
    }

    public PT3 getT3()
    {
        return this._t3_;
    }

    public void setT3(PT3 node)
    {
        if(this._t3_ != null)
        {
            this._t3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._t2_)
            + toString(this._egale_)
            + toString(this._t3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._t2_ == child)
        {
            this._t2_ = null;
            return;
        }

        if(this._egale_ == child)
        {
            this._egale_ = null;
            return;
        }

        if(this._t3_ == child)
        {
            this._t3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._t2_ == oldChild)
        {
            setT2((PT2) newChild);
            return;
        }

        if(this._egale_ == oldChild)
        {
            setEgale((TEgale) newChild);
            return;
        }

        if(this._t3_ == oldChild)
        {
            setT3((PT3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
