/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AExp2T6 extends PT6
{
    private PT6 _t6_;
    private TPoints _points_;
    private PT7 _t7_;

    public AExp2T6()
    {
        // Constructor
    }

    public AExp2T6(
        @SuppressWarnings("hiding") PT6 _t6_,
        @SuppressWarnings("hiding") TPoints _points_,
        @SuppressWarnings("hiding") PT7 _t7_)
    {
        // Constructor
        setT6(_t6_);

        setPoints(_points_);

        setT7(_t7_);

    }

    @Override
    public Object clone()
    {
        return new AExp2T6(
            cloneNode(this._t6_),
            cloneNode(this._points_),
            cloneNode(this._t7_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExp2T6(this);
    }

    public PT6 getT6()
    {
        return this._t6_;
    }

    public void setT6(PT6 node)
    {
        if(this._t6_ != null)
        {
            this._t6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t6_ = node;
    }

    public TPoints getPoints()
    {
        return this._points_;
    }

    public void setPoints(TPoints node)
    {
        if(this._points_ != null)
        {
            this._points_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._points_ = node;
    }

    public PT7 getT7()
    {
        return this._t7_;
    }

    public void setT7(PT7 node)
    {
        if(this._t7_ != null)
        {
            this._t7_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t7_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._t6_)
            + toString(this._points_)
            + toString(this._t7_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._t6_ == child)
        {
            this._t6_ = null;
            return;
        }

        if(this._points_ == child)
        {
            this._points_ = null;
            return;
        }

        if(this._t7_ == child)
        {
            this._t7_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._t6_ == oldChild)
        {
            setT6((PT6) newChild);
            return;
        }

        if(this._points_ == oldChild)
        {
            setPoints((TPoints) newChild);
            return;
        }

        if(this._t7_ == oldChild)
        {
            setT7((PT7) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
