/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AExp2 extends PExp2
{
    private PExp _exp_;
    private PSuiv _suiv_;

    public AExp2()
    {
        // Constructor
    }

    public AExp2(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PSuiv _suiv_)
    {
        // Constructor
        setExp(_exp_);

        setSuiv(_suiv_);

    }

    @Override
    public Object clone()
    {
        return new AExp2(
            cloneNode(this._exp_),
            cloneNode(this._suiv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExp2(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PSuiv getSuiv()
    {
        return this._suiv_;
    }

    public void setSuiv(PSuiv node)
    {
        if(this._suiv_ != null)
        {
            this._suiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._suiv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._suiv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._suiv_ == child)
        {
            this._suiv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._suiv_ == oldChild)
        {
            setSuiv((PSuiv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
