/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInsttantqueInst extends PInst
{
    private PInsttantque _insttantque_;

    public AInsttantqueInst()
    {
        // Constructor
    }

    public AInsttantqueInst(
        @SuppressWarnings("hiding") PInsttantque _insttantque_)
    {
        // Constructor
        setInsttantque(_insttantque_);

    }

    @Override
    public Object clone()
    {
        return new AInsttantqueInst(
            cloneNode(this._insttantque_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInsttantqueInst(this);
    }

    public PInsttantque getInsttantque()
    {
        return this._insttantque_;
    }

    public void setInsttantque(PInsttantque node)
    {
        if(this._insttantque_ != null)
        {
            this._insttantque_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._insttantque_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._insttantque_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._insttantque_ == child)
        {
            this._insttantque_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._insttantque_ == oldChild)
        {
            setInsttantque((PInsttantque) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
