/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstsiInst extends PInst
{
    private PInstsi _instsi_;

    public AInstsiInst()
    {
        // Constructor
    }

    public AInstsiInst(
        @SuppressWarnings("hiding") PInstsi _instsi_)
    {
        // Constructor
        setInstsi(_instsi_);

    }

    @Override
    public Object clone()
    {
        return new AInstsiInst(
            cloneNode(this._instsi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstsiInst(this);
    }

    public PInstsi getInstsi()
    {
        return this._instsi_;
    }

    public void setInstsi(PInstsi node)
    {
        if(this._instsi_ != null)
        {
            this._instsi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instsi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instsi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instsi_ == child)
        {
            this._instsi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instsi_ == oldChild)
        {
            setInstsi((PInstsi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
