/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstretourInst extends PInst
{
    private PInstretour _instretour_;

    public AInstretourInst()
    {
        // Constructor
    }

    public AInstretourInst(
        @SuppressWarnings("hiding") PInstretour _instretour_)
    {
        // Constructor
        setInstretour(_instretour_);

    }

    @Override
    public Object clone()
    {
        return new AInstretourInst(
            cloneNode(this._instretour_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstretourInst(this);
    }

    public PInstretour getInstretour()
    {
        return this._instretour_;
    }

    public void setInstretour(PInstretour node)
    {
        if(this._instretour_ != null)
        {
            this._instretour_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instretour_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instretour_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instretour_ == child)
        {
            this._instretour_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instretour_ == oldChild)
        {
            setInstretour((PInstretour) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
