/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstaffectInst extends PInst
{
    private PInstaffect _instaffect_;

    public AInstaffectInst()
    {
        // Constructor
    }

    public AInstaffectInst(
        @SuppressWarnings("hiding") PInstaffect _instaffect_)
    {
        // Constructor
        setInstaffect(_instaffect_);

    }

    @Override
    public Object clone()
    {
        return new AInstaffectInst(
            cloneNode(this._instaffect_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstaffectInst(this);
    }

    public PInstaffect getInstaffect()
    {
        return this._instaffect_;
    }

    public void setInstaffect(PInstaffect node)
    {
        if(this._instaffect_ != null)
        {
            this._instaffect_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instaffect_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instaffect_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instaffect_ == child)
        {
            this._instaffect_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instaffect_ == oldChild)
        {
            setInstaffect((PInstaffect) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
