/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstvideInst extends PInst
{
    private PInstvide _instvide_;

    public AInstvideInst()
    {
        // Constructor
    }

    public AInstvideInst(
        @SuppressWarnings("hiding") PInstvide _instvide_)
    {
        // Constructor
        setInstvide(_instvide_);

    }

    @Override
    public Object clone()
    {
        return new AInstvideInst(
            cloneNode(this._instvide_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstvideInst(this);
    }

    public PInstvide getInstvide()
    {
        return this._instvide_;
    }

    public void setInstvide(PInstvide node)
    {
        if(this._instvide_ != null)
        {
            this._instvide_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instvide_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instvide_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instvide_ == child)
        {
            this._instvide_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instvide_ == oldChild)
        {
            setInstvide((PInstvide) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
