/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstappelInst extends PInst
{
    private PInstappel _instappel_;

    public AInstappelInst()
    {
        // Constructor
    }

    public AInstappelInst(
        @SuppressWarnings("hiding") PInstappel _instappel_)
    {
        // Constructor
        setInstappel(_instappel_);

    }

    @Override
    public Object clone()
    {
        return new AInstappelInst(
            cloneNode(this._instappel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstappelInst(this);
    }

    public PInstappel getInstappel()
    {
        return this._instappel_;
    }

    public void setInstappel(PInstappel node)
    {
        if(this._instappel_ != null)
        {
            this._instappel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instappel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instappel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instappel_ == child)
        {
            this._instappel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instappel_ == oldChild)
        {
            setInstappel((PInstappel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
