/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstsinon extends PInstsinon
{
    private TSinon _sinon_;
    private PInstbloc _instbloc_;

    public AInstsinon()
    {
        // Constructor
    }

    public AInstsinon(
        @SuppressWarnings("hiding") TSinon _sinon_,
        @SuppressWarnings("hiding") PInstbloc _instbloc_)
    {
        // Constructor
        setSinon(_sinon_);

        setInstbloc(_instbloc_);

    }

    @Override
    public Object clone()
    {
        return new AInstsinon(
            cloneNode(this._sinon_),
            cloneNode(this._instbloc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstsinon(this);
    }

    public TSinon getSinon()
    {
        return this._sinon_;
    }

    public void setSinon(TSinon node)
    {
        if(this._sinon_ != null)
        {
            this._sinon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinon_ = node;
    }

    public PInstbloc getInstbloc()
    {
        return this._instbloc_;
    }

    public void setInstbloc(PInstbloc node)
    {
        if(this._instbloc_ != null)
        {
            this._instbloc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instbloc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sinon_)
            + toString(this._instbloc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sinon_ == child)
        {
            this._sinon_ = null;
            return;
        }

        if(this._instbloc_ == child)
        {
            this._instbloc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sinon_ == oldChild)
        {
            setSinon((TSinon) newChild);
            return;
        }

        if(this._instbloc_ == oldChild)
        {
            setInstbloc((PInstbloc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
