/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALdfDvglobalsProgramme extends PProgramme
{
    private POptdv _optdv_;
    private PLdf _ldf_;

    public ALdfDvglobalsProgramme()
    {
        // Constructor
    }

    public ALdfDvglobalsProgramme(
        @SuppressWarnings("hiding") POptdv _optdv_,
        @SuppressWarnings("hiding") PLdf _ldf_)
    {
        // Constructor
        setOptdv(_optdv_);

        setLdf(_ldf_);

    }

    @Override
    public Object clone()
    {
        return new ALdfDvglobalsProgramme(
            cloneNode(this._optdv_),
            cloneNode(this._ldf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALdfDvglobalsProgramme(this);
    }

    public POptdv getOptdv()
    {
        return this._optdv_;
    }

    public void setOptdv(POptdv node)
    {
        if(this._optdv_ != null)
        {
            this._optdv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optdv_ = node;
    }

    public PLdf getLdf()
    {
        return this._ldf_;
    }

    public void setLdf(PLdf node)
    {
        if(this._ldf_ != null)
        {
            this._ldf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optdv_)
            + toString(this._ldf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optdv_ == child)
        {
            this._optdv_ = null;
            return;
        }

        if(this._ldf_ == child)
        {
            this._ldf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optdv_ == oldChild)
        {
            setOptdv((POptdv) newChild);
            return;
        }

        if(this._ldf_ == oldChild)
        {
            setLdf((PLdf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
