/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALdfProgramme extends PProgramme
{
    private PLdf _ldf_;

    public ALdfProgramme()
    {
        // Constructor
    }

    public ALdfProgramme(
        @SuppressWarnings("hiding") PLdf _ldf_)
    {
        // Constructor
        setLdf(_ldf_);

    }

    @Override
    public Object clone()
    {
        return new ALdfProgramme(
            cloneNode(this._ldf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALdfProgramme(this);
    }

    public PLdf getLdf()
    {
        return this._ldf_;
    }

    public void setLdf(PLdf node)
    {
        if(this._ldf_ != null)
        {
            this._ldf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ldf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ldf_ == child)
        {
            this._ldf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ldf_ == oldChild)
        {
            setLdf((PLdf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
