/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ANonT5 extends PT5
{
    private TNon _non_;
    private PT5 _t5_;

    public ANonT5()
    {
        // Constructor
    }

    public ANonT5(
        @SuppressWarnings("hiding") TNon _non_,
        @SuppressWarnings("hiding") PT5 _t5_)
    {
        // Constructor
        setNon(_non_);

        setT5(_t5_);

    }

    @Override
    public Object clone()
    {
        return new ANonT5(
            cloneNode(this._non_),
            cloneNode(this._t5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANonT5(this);
    }

    public TNon getNon()
    {
        return this._non_;
    }

    public void setNon(TNon node)
    {
        if(this._non_ != null)
        {
            this._non_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._non_ = node;
    }

    public PT5 getT5()
    {
        return this._t5_;
    }

    public void setT5(PT5 node)
    {
        if(this._t5_ != null)
        {
            this._t5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._non_)
            + toString(this._t5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._non_ == child)
        {
            this._non_ = null;
            return;
        }

        if(this._t5_ == child)
        {
            this._t5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._non_ == oldChild)
        {
            setNon((TNon) newChild);
            return;
        }

        if(this._t5_ == oldChild)
        {
            setT5((PT5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
