/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASuiv extends PSuiv
{
    private TPoints _points_;
    private PExp _exp_;

    public ASuiv()
    {
        // Constructor
    }

    public ASuiv(
        @SuppressWarnings("hiding") TPoints _points_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setPoints(_points_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new ASuiv(
            cloneNode(this._points_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuiv(this);
    }

    public TPoints getPoints()
    {
        return this._points_;
    }

    public void setPoints(TPoints node)
    {
        if(this._points_ != null)
        {
            this._points_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._points_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._points_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._points_ == child)
        {
            this._points_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._points_ == oldChild)
        {
            setPoints((TPoints) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
