/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AT1Exp extends PExp
{
    private PT1 _t1_;

    public AT1Exp()
    {
        // Constructor
    }

    public AT1Exp(
        @SuppressWarnings("hiding") PT1 _t1_)
    {
        // Constructor
        setT1(_t1_);

    }

    @Override
    public Object clone()
    {
        return new AT1Exp(
            cloneNode(this._t1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAT1Exp(this);
    }

    public PT1 getT1()
    {
        return this._t1_;
    }

    public void setT1(PT1 node)
    {
        if(this._t1_ != null)
        {
            this._t1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._t1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._t1_ == child)
        {
            this._t1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._t1_ == oldChild)
        {
            setT1((PT1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
