/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AT4T3 extends PT3
{
    private PT4 _t4_;

    public AT4T3()
    {
        // Constructor
    }

    public AT4T3(
        @SuppressWarnings("hiding") PT4 _t4_)
    {
        // Constructor
        setT4(_t4_);

    }

    @Override
    public Object clone()
    {
        return new AT4T3(
            cloneNode(this._t4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAT4T3(this);
    }

    public PT4 getT4()
    {
        return this._t4_;
    }

    public void setT4(PT4 node)
    {
        if(this._t4_ != null)
        {
            this._t4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._t4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._t4_ == child)
        {
            this._t4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._t4_ == oldChild)
        {
            setT4((PT4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
