/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AT5T4 extends PT4
{
    private PT5 _t5_;

    public AT5T4()
    {
        // Constructor
    }

    public AT5T4(
        @SuppressWarnings("hiding") PT5 _t5_)
    {
        // Constructor
        setT5(_t5_);

    }

    @Override
    public Object clone()
    {
        return new AT5T4(
            cloneNode(this._t5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAT5T4(this);
    }

    public PT5 getT5()
    {
        return this._t5_;
    }

    public void setT5(PT5 node)
    {
        if(this._t5_ != null)
        {
            this._t5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._t5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._t5_ == child)
        {
            this._t5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._t5_ == oldChild)
        {
            setT5((PT5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
