/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AT6T5 extends PT5
{
    private PT6 _t6_;

    public AT6T5()
    {
        // Constructor
    }

    public AT6T5(
        @SuppressWarnings("hiding") PT6 _t6_)
    {
        // Constructor
        setT6(_t6_);

    }

    @Override
    public Object clone()
    {
        return new AT6T5(
            cloneNode(this._t6_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAT6T5(this);
    }

    public PT6 getT6()
    {
        return this._t6_;
    }

    public void setT6(PT6 node)
    {
        if(this._t6_ != null)
        {
            this._t6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t6_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._t6_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._t6_ == child)
        {
            this._t6_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._t6_ == oldChild)
        {
            setT6((PT6) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
