/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AT7T6 extends PT6
{
    private PT7 _t7_;

    public AT7T6()
    {
        // Constructor
    }

    public AT7T6(
        @SuppressWarnings("hiding") PT7 _t7_)
    {
        // Constructor
        setT7(_t7_);

    }

    @Override
    public Object clone()
    {
        return new AT7T6(
            cloneNode(this._t7_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAT7T6(this);
    }

    public PT7 getT7()
    {
        return this._t7_;
    }

    public void setT7(PT7 node)
    {
        if(this._t7_ != null)
        {
            this._t7_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t7_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._t7_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._t7_ == child)
        {
            this._t7_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._t7_ == oldChild)
        {
            setT7((PT7) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
