/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ATernopInst extends PInst
{
    private PTernop _ternop_;

    public ATernopInst()
    {
        // Constructor
    }

    public ATernopInst(
        @SuppressWarnings("hiding") PTernop _ternop_)
    {
        // Constructor
        setTernop(_ternop_);

    }

    @Override
    public Object clone()
    {
        return new ATernopInst(
            cloneNode(this._ternop_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATernopInst(this);
    }

    public PTernop getTernop()
    {
        return this._ternop_;
    }

    public void setTernop(PTernop node)
    {
        if(this._ternop_ != null)
        {
            this._ternop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ternop_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ternop_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ternop_ == child)
        {
            this._ternop_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ternop_ == oldChild)
        {
            setTernop((PTernop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
