/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.analysis;

import java.util.*;
import sc.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALdfDvglobalsProgramme(ALdfDvglobalsProgramme node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALdfProgramme(ALdfProgramme node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOptdvOptdv(AOptdvOptdv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALdvLdv(ALdvLdv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADvLdv(ADvLdv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASuiteLdvLdvsuite(ASuiteLdvLdvsuite node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASuiteDvLdvsuite(ASuiteDvLdvsuite node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarDv(AVarDv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATableauDv(ATableauDv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALdfLdf(ALdfLdf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALdfVideLdf(ALdfVideLdf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADfDf(ADfDf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADfSansvariablesDf(ADfSansvariablesDf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASansLparam(ASansLparam node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAvecLparam(AAvecLparam node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstaffectInst(AInstaffectInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstblocInst(AInstblocInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstsiInst(AInstsiInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInsttantqueInst(AInsttantqueInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstappelInst(AInstappelInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstretourInst(AInstretourInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstecritureInst(AInstecritureInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstvideInst(AInstvideInst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstaffect(AInstaffect node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstbloc(AInstbloc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALinstLinst(ALinstLinst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALinstvideLinst(ALinstvideLinst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASinonInstsi(ASinonInstsi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASiInstsi(ASiInstsi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstsinon(AInstsinon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInsttantque(AInsttantque node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstappel(AInstappel node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstretour(AInstretour node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstecriture(AInstecriture node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstvide(AInstvide node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuExp(AOuExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAT1Exp(AT1Exp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEtT1(AEtT1 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAT2T1(AT2T1 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInfT2(AInfT2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEgaleT2(AEgaleT2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAT3T2(AT3T2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPlusT3(APlusT3 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMinusT3(AMinusT3 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAT4T3(AT4T3 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultT4(AMultT4 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADiviseT4(ADiviseT4 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAT5T4(AT5T4 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANonT5(ANonT5 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAT6T5(AT6T5 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANombreT6(ANombreT6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAppelfT6(AAppelfT6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarT6(AVarT6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParT6(AParT6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALireT6(ALireT6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATabVar(ATabVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarVar(AVarVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALexpLexp(ALexpLexp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideLexp(AVideLexp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALsuiteLexpSuite(ALsuiteLexpSuite node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideLexpSuite(AVideLexpSuite node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAppelf(AAppelf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEspaces(TEspaces node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCommentaire(TCommentaire node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVirgule(TVirgule node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDivise(TDivise node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPointVirgule(TPointVirgule node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMinus(TMinus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParentheseOuvrante(TParentheseOuvrante node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParentheseFermante(TParentheseFermante node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCrochetOuvrant(TCrochetOuvrant node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCrochetFermant(TCrochetFermant node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAccoladeOuvrante(TAccoladeOuvrante node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAccoladeFermante(TAccoladeFermante node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEgale(TEgale node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInferieur(TInferieur node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEt(TEt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOu(TOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNon(TNon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPlus(TPlus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSi(TSi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAlors(TAlors node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSinon(TSinon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTantque(TTantque node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFaire(TFaire node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTType(TType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRetour(TRetour node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLire(TLire node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEcrire(TEcrire node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNombre(TNombre node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIdentif(TIdentif node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
